items = ["anurag", "18-02-2002", 19]
print(items)
items.append("new element")
print(items)
items.extend(['intem3'])
print(items)
items.insert(3,"between")
print(items)
items.remove("between")
print(items)
items.pop(3)
print(items)